version: '3'
services:
  db:
    container_name: art_db
    image: mysql:8.0
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: art_mysql
      MYSQL_ROOT_PASSWORD: sAA2rnf42
    ports:
      - "3306:3306"

  app:
    container_name: art_app
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
    volumes:
      - ../:/var/www/
    ports:
        - "8000:8000"

volumes:
  db:
  app:
  redis:
